version: '3'

services:
  redis:
    image: redis
    volumes:
      - redis_db_data:/data/admin/redis
    restart: always
    
  mongo:
      image: mongo
      restart: always
      volumes: 
        - mongo_db_data:/data/admin/mongo
  
  admin: 
    depends_on: 
      - redis
      - mongo
    build:
      context: .
    # image: nest-admin
    restart: always
    ports:
      - 4221:4221
    environment: 
      MONGO_HOST: mongo
      REDIS_HOST: redis
    volumes: 
      - nest_admin:/app

  mongo-express:
    image: mongo-express
    restart: alwagitys
    ports:
      - 8081:8081

  # nginx:
  #   depends_on:
  #     - ela
  #   image: nginx
  #   ports:
  #     - 80:80
  #   volumes: 
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes: 
  nest_admin:
  redis_db_data: 
  mongo_db_data: